import type { Metadata } from "next";
import {Livvic} from "next/font/google";
import "./globals.css";
import ClientProviders from "@/lib/provider/client-providers";
import { Toaster } from "sonner";

const livvic = Livvic({
  subsets: ["latin"],
  variable: "--font-livvic",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
          className={`${livvic.className} ${livvic.variable}  antialiased`}
      >
      <ClientProviders>
        {children}
      </ClientProviders>
      <Toaster richColors position="top-center" />
      </body>
      </html>
  );
}
